### ISSUE TITLE
Add option to configure update interval

### ISSUE THREAD

**Issue by Mosher23** [marcolivierarsenault/moonraker-home-assistant#135]
Hello,

please add option for the update interval of the sensors.
e.g. 1 sec, 5, sec, 15 sec,.....

Thank you in advance

**Comment by Kixel** [comment]
Hi,
I'd love this as well. My filament sensor is a bit finicky and sometimes reports no filament for ~1s, but mainsail can't really handle short runouts (or I'm too stupid), so I'd love to build a solution in HomeAssistant. 30 seconds is far too long for detecting these (and avoiding actual runout; printing too fast for that). 
The octoprint MQTT solution worked perfectly for homeassistant (i.e. instant updates), but since i changed to mainsail, this is kind of a missing feature.

**Comment by marcolivierarsenault** [comment]
This won't be done, will be part of pull mode (version 1.0.0)  (no ETA)
