### ISSUE TITLE
Slow sensor update

### ISSUE THREAD

**Issue by MattiaConfalonieri** [marcolivierarsenault/moonraker-home-assistant#159]
Creality Sonic Pad / Ender 5 S1

No problem with integration, all sensor give me the save value that I can see in webinterface.

The sensor update time is little bit lazy, when I move the extruder via web, web page update the value and home assistant take 30 second do to it.

There is something that I can do to get better performance?

**Comment by marcolivierarsenault** [comment]
We are looking to move this integration to push instead of pull, that will fix the delay. In the mean time we won't change anything. That being said you could manually change https://github.com/marcolivierarsenault/moonraker-home-assistant/blob/main/custom_components/moonraker/__init__.py#L29 on your setup to get it quicker
