### ISSUE TITLE
Rename entities when renaming integration and ask for printer name on install

### ISSUE THREAD

**Issue by iMartyn** [marcolivierarsenault/moonraker-home-assistant#166]
## Is your feature request related to a problem? Please describe.

It's annoying that you cannot specify a name for the printer when you create the integration.  I have multiple moonrakers on my print host, and it's called `xps`.  Because of this when I add my ender3 I end up with a load of sensors called things like `xps Current Layer`.  I click rename in the integrations tab of homeassistant and rename from `xps` to `ender3` and the sensors stay the same - `xps Current Layer`.

## Describe your setup

I run on an old laptop using debian and kiuah multiple klippers.

## Describe the solution you'd like

Ideally both asking for the name of the printer when installing the integration and if you rename the integration, taking note of it and renaming the sensors to match.

**Comment by marcolivierarsenault** [comment]
Can you validate you are on the latest version of the app.
Because I can rename the Device and Entity names match accordingly 

![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/2634090/a5497791-0062-4f50-8357-035dbf80565c)


If you don't have this, how/where do you rename your device?
