### ISSUE TITLE
Suport Fan Control

### ISSUE THREAD

**Issue by gosoares** [marcolivierarsenault/moonraker-home-assistant#322]
## Version of the moonraker integration

1.2.0

## Describe your setup

Creality K1 Printer with Klipper, Moonraker, Fluidd, Mainsail

## Describe the bug

I have 4 numbers in my integration, one for the light, and 3 for the fans (hotend, side and rear). The light works fine, but the fans don´t, when i set the fans to some value, they do nothing on the machine, and a few seconds later, they values are updated in home assistant to a really low value:

![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/9306656/60da69e6-64fb-47bd-9d5d-55f5138e53d7)

On the mainsail or fluidd interface, i can control them correctly, so it must be a problem in the integration.

## Moonraker Logs

[logs.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/14971511/logs.log)

**Comment by thewolfman56** [comment]
From what I noticed on my K1Max, the printer recognizes the fan speed as a range 0-255.  The integration appears to pull the data from the printer as a percentage of that range, but when you set the fan speed in Home Assistant using the integration, it sends the fan speed as a number instead of a percentage of the range.  For example, if you set the fan speed at 70% in Home Assistant, it sets the fan speed in the printer as 0.70 (which is 0.70 in a range of 0-255).

The LED works correctly because the printer has a range of 0-1 for the LED, so the percentages work correctly.

**Comment by marcolivierarsenault** [comment]
Fan should not be controlable just yet. We thought they would be excluded. We don't have adjustable fans so we can't test it

**Comment by marcolivierarsenault** [comment]
suplicate of #229
