### ISSUE TITLE
Integration sync question

### ISSUE THREAD

**Issue by DrFate09** [marcolivierarsenault/moonraker-home-assistant#76]
Not a bug ticket but a question. For your integration, now that you have support for macros and fans, etc, if I add a new macro or fan, etc, to my Klipper instance, will your integration automatically detect and add it to HA as an entity? Or do we need to re-sync/re-setup our Klipper instance in HA?

**Comment by cashew22** [comment]
Hi @DrFate09 I think if you use the "Reload" button in the integration menu it will work.

![image](https://user-images.githubusercontent.com/4152795/227796828-0db45662-6257-447b-b3b3-c32a8e6a25ec.png)

I can't test it right now because I'm currently printing (tough life) , if you can test it, can you post the result here :) thanks

**Comment by marcolivierarsenault** [comment]
@DrFate09 yes solution proposed by @cashew22 does work.

Add you macro in Klipper, restart Klipper. 

Then in HA, simply click Reload, as shown in the above screenshot and it will get added

**Comment by DrFate09** [comment]
Thanks for looking into this and confirming the procedure! Would you mind adding this as a note in the WIKI, could be useful for others to know. Thanks!
