### ISSUE TITLE
Add extra sensor for slicer estimate.

### ISSUE THREAD

**Issue by WolfeCub** [marcolivierarsenault/moonraker-home-assistant#97]
## Is your feature request related to a problem? Please describe.

I currently have my slicer very dialed in and the times I get there are usually accurate to within 5 minutes or so. Currently the [calculate eta seems to be doing a bunch of estimates using the fillament](https://github.com/marcolivierarsenault/moonraker-home-assistant/blob/258d2958de8d77bc65f9561d14b50c8926ead23f/custom_components/moonraker/sensor.py#L476). This doesn't seem to produce very accurate results for me. For example here's a print I'm running now:
![image](https://user-images.githubusercontent.com/1369773/229857725-804fe601-51c6-4b88-9216-82d49c14fb67.png)
![image](https://user-images.githubusercontent.com/1369773/229857798-a258d114-0612-4df2-908c-05477d3e7408.png)

The estimate provided by home assistant is around 40 minutes off.

## Describe the solution you'd like

I'd like a sensor that exposes the raw slicer time estimate so that I can simply calculate `slicer_estimate - time_elapsed` to get a more accurate print time.

**Comment by WolfeCub** [comment]
^ Opened a PR for this. Let me know if there's any changes needed there.

**Comment by calebeby** [comment]
Hi, any chance you could provide a "Slicer Print ETA" field (formatted like the "Print ETA" field but using the estimate/data from the slicer)? So the estimate would be the same as "Slicer Print Time Left Estimate" but just formatted as a timestamp instead of a duration.

Happy to open a new issue if you'd like.

And thanks for making this integration, it is so cool!
